name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create Docker Buildx builder
      run: docker buildx create --use

    - name: Build Docker image
      run: docker buildx build --platform linux/arm64 --tag my-image-name:latest --output type=docker,dest=image.tar .

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: image.tar

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up GitHub CLI
      uses: cli/gh-action@v3

    - name: Authenticate GitHub CLI
      run: gh auth login --with-token ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      run: |
        TAG_NAME=$(git describe --tags)
        RELEASE_NOTES="test"
        gh release create latest --target $TAG_NAME --notes "$RELEASE_NOTES" ./path_to_assets.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
